services:
  - type: web
    name: insta-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python ultra_fast_boss_bot.py
    envVars:
      - key: PORT
        value: 10000
